# Generated by Django 5.1.4 on 2025-01-09 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статья",
            },
        ),
        migrations.AlterModelOptions(
            name="articlecategory",
            options={
                "verbose_name": "Категория статьи",
                "verbose_name_plural": "Категория статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="initiative",
            options={
                "verbose_name": "Инициатива",
                "verbose_name_plural": "Инициатива",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="article",
            name="image_webp",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="initiative",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="initiative",
            name="image_webp",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="project",
            name="image_webp",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="cat_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.articlecategory",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="initiative_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.initiative",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
