# Generated by Django 5.1.4 on 2025-01-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_article_options_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/webp/'),
        ),
    ]
