# Generated by Django 5.1.4 on 2025-01-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_image_webp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_webp',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
