# Generated by Django 5.1.4 on 2025-03-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_article_image_webp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_webp",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="initiative",
            name="image_webp",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="project",
            name="image_detail_webp",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="project",
            name="image_webp",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
