# Generated by Django 5.1.4 on 2025-01-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_image_webp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_webp',
        ),
    ]
