# Generated by Django 4.2.20 on 2025-03-19 12:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_article_image_webp_initiative_image_webp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="detail_text",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="image_detail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="article",
            name="image_detail_webp",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="initiative",
            name="detail_text",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="image_detail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="initiative",
            name="image_detail_webp",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
