# Generated by Django 5.1.4 on 2025-01-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_image_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/webp/'),
        ),
    ]
