# Generated by Django 5.1.7 on 2025-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_article_detail_text_article_image_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="json_blocks",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
