# Generated by Django 5.1.7 on 2025-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_project_json_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="json_blocks",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="initiative",
            name="json_blocks",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
