# Generated by Django 5.1.4 on 2025-01-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_image_alter_project_image_webp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
