# Generated by Django 5.1.4 on 2025-01-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_article_image_webp_initiative_image_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
