# Generated by Django 5.1.4 on 2025-01-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_article_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
