# Generated by Django 5.1.4 on 2025-01-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_article_text_project_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='text',
        ),
    ]
