# Generated by Django 5.1.4 on 2025-01-08 12:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_remove_project_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="detail_text",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
