# Generated by Django 5.1.4 on 2025-01-08 12:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_project_detail_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="detail_text",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
