name: Deploy Django

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker build --build-arg DJANGO_ENV=production -t ${{ secrets.DOCKER_USER }}/django-prod:latest .
          docker push ${{ secrets.DOCKER_USER }}/django-prod:latest

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/ar69tem/data/www/deep-cosmo.ru/opt/django-app
            
            # Создаем .env
            cat << EOF > .env
            DOCKER_USER=${{ secrets.DOCKER_USER }}
            SECURE=True
            DEBUG=${{ secrets.DJANGO_DEBUG }}
            SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            SITE_URL=${{ secrets.DJANGO_SITE_URL }}
            ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}
            CORS_ALLOWED_ORIGINS=${{ secrets.DJANGO_CORS_ALLOWED_ORIGINS }}
            DB_ENGINE=django.db.backends.sqlite3
            DB_NAME=/app/db/prod.sqlite3
            EOF
            chmod 600 .env

            # Первый запуск
            if [ ! -f db/prod.sqlite3 ]; then
              docker compose run web python manage.py migrate
            fi

            # Обновление
            docker compose pull
            docker compose down
            docker compose up -d